name: file-downloader v2

# set timer: at minute 45
on:
  schedule:
  - cron: 45 * * * *

#on: push

jobs: 
  download-file:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: run-wget
        run: |
           wget -N "https://www.msss.gouv.qc.ca/professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv"
           wget -N "https://www.msss.gouv.qc.ca/professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours_nbpers.csv"

      - name: commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add *.csv
          git mv -f "Releve_horaire_urgences_7jours.csv" "data/urgence.csv"
          git mv -f "Releve_horaire_urgences_7jours_nbpers.csv" "data/urgence_time.csv"
          git commit -am "Scheduled Github Action on $(date)"
          git push origin main
