name: save_wait_time_to_files

# on: push

## script collects average wait times from previous day 
## will run only once per day
# set timer = 14:05 utc
on:
 schedule:
 - cron: 5 14 * * *

jobs:
  get-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     
      - name: Run script
        run: python script_wait_times.py
        
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add tables/*
          git commit -am "Scheduled Github Action on $(date)"
          git push origin main
